export const MOVIMENTACOES = {
  ENTRADA_NF: 101,
  ESTORNO_ENTRADA_NF: 102,
  EQUIPAMENTO_PARA_ESTOQUE: 201,
  ESTORNO_EQUIPAMENTO_PARA_ESTOQUE: 202,
  ESTOQUE_PARA_EQUIPAMENTO: 261,
  ESTORNO_ESTOQUE_PARA_EQUIPAMENTO: 262,
  ESTOQUE_PARA_FORNECEDOR: 361,
  ESTORNO_ESTOQUE_PARA_FORNECEDOR: 362,
  FORNECEDOR_PARA_ESTOQUE: 461,
  ESTORNO_FORNECEDOR_PARA_ESTOQUE: 462,
  RETORNO_REFORMA: 551,
  ESTORNO_RETORNO_REFORMA: 552,
  TRANSFERENCIA_ESTOQUES: 601,
  ESTORNO_TRANSFERENCIA_ESTOQUES: 602,
  ESTOQUE_PARA_SUCATA: 751,
  ESTORNO_ESTOQUE_PARA_SUCATA: 752,
} as const;

export const descricaoMovimentacao: Record<number, string> = {
  101: "Entrada de material no estoque por Nota Fiscal",
  102: "Estorno do movimento 101",
  201: "Entrada de material no estoque por saída de equipamento",
  202: "Estorno do movimento 201",
  261: "Saída de material do estoque para equipamento",
  262: "Estorno do movimento 261",
  361: "Saída de material do estoque para fornecedor",
  362: "Estorno do movimento 361",
  461: "Retorno de material do fornecedor para estoque",
  462: "Estorno do movimento 461",
  551: "Retorno de reforma: usado para reformado, com nova vida",
  552: "Estorno do movimento 551",
  601: "Transferência entre estoques",
  602: "Estorno da transferência 601",
  751: "Saída de material do estoque para depósito de sucata",
  752: "Estorno do movimento 751",
};
