'use client';
import {useMemo,useState} from 'react';
import {AppShell} from '@/components/AppShell';
import {stockTires,Tire,suppliers} from '@/lib/demoData';
import {PackagePlus,Search,Factory,ArrowLeftRight,Trash2,FileText,X,CheckCircle2} from 'lucide-react';

type View='estoque'|'entrada'|'reforma'|'transferencia';
export default function EstoquePage(){
 const [view,setView]=useState<View>('estoque'); const [tires,setTires]=useState<Tire[]>(stockTires); const [selected,setSelected]=useState<string[]>([]); const [search,setSearch]=useState(''); const [msg,setMsg]=useState('');
 const filtered=useMemo(()=>tires.filter(t=>!search||t.fogo.toLowerCase().includes(search.toLowerCase())||t.material.toLowerCase().includes(search.toLowerCase())),[tires,search]);
 const groups={NOVO:filtered.filter(t=>t.status==='NOVO'),USADO:filtered.filter(t=>t.status==='USADO'),REFORMADO:filtered.filter(t=>t.status==='REFORMADO'),EM_REFORMA:filtered.filter(t=>t.status==='EM_REFORMA')};
 function toggle(f:string){setSelected(s=>s.includes(f)?s.filter(x=>x!==f):[...s,f])}
 function sendReforma(){const chosen=tires.filter(t=>selected.includes(t.fogo));if(chosen.some(t=>t.status!=='USADO')){setMsg('Somente pneus USADOS podem ser enviados para reforma. Pneus NOVOS e REFORMADOS estão bloqueados.');return}setTires(ts=>ts.map(t=>selected.includes(t.fogo)?{...t,status:'EM_REFORMA',fornecedor:suppliers[0]}:t));setMsg(`Lote RF-210826-01 criado com ${selected.length} pneu(s). Prazo: 7 dias.`);setSelected([])}
 function sucatear(){const chosen=tires.filter(t=>selected.includes(t.fogo));if(chosen.some(t=>t.status==='NOVO')){setMsg('Pneu NOVO não pode ser sucateado.');return}setTires(ts=>ts.filter(t=>!selected.includes(t.fogo)));setMsg(`${selected.length} pneu(s) enviados para análise/sucata. Log 751 preparado.`);setSelected([])}
 return <AppShell><div className="content"><div className="pageHead"><div><span className="eyebrow">ESTOQUE</span><h2>Gestão de pneus em estoque</h2><p>Entrada por NF, lotes, reforma, transferências e saldo disponível.</p></div><div className="headActions"><button className="btn primary" onClick={()=>setView('entrada')}><PackagePlus size={17}/> Entrada por NF</button><button className="btn" onClick={()=>setView('transferencia')}><ArrowLeftRight size={17}/> Transferir</button></div></div>
 {msg&&<div className="flash"><CheckCircle2 size={18}/>{msg}</div>}
 <div className="kpis"><div className="kpi blue"><small>Pneus novos</small><b>{groups.NOVO.length}</b><span>Proibido reforma e sucata</span></div><div className="kpi green"><small>Pneus reformados</small><b>{groups.REFORMADO.length}</b><span>Proibido nova reforma</span></div><div className="kpi orange"><small>Pneus usados</small><b>{groups.USADO.length}</b><span>Movimentação liberada</span></div><div className="kpi purple"><small>Em reforma</small><b>{groups.EM_REFORMA.length}</b><span>Prazo padrão: 7 dias</span></div></div>
 <div className="stockToolbar"><div className="finderInput compact"><Search size={17}/><input placeholder="Pesquisar vários pneus por nº fogo ou material" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{selected.length} selecionado(s)</span><button className="btn purple" disabled={!selected.length} onClick={sendReforma}><Factory size={16}/> Enviar para reforma</button><button className="btn dangerBtn" disabled={!selected.length} onClick={sucatear}><Trash2 size={16}/> Enviar para sucata</button><button className="btn" disabled={!selected.length} onClick={()=>setMsg('Lote de movimentação múltipla preparado para os pneus selecionados.')}><FileText size={16}/> Criar lote</button></div>
 {(['NOVO','REFORMADO','USADO','EM_REFORMA'] as const).map(status=><StockGroup key={status} title={{NOVO:'Pneus novos',REFORMADO:'Pneus reformados',USADO:'Pneus usados',EM_REFORMA:'Pneus em reforma'}[status]} rows={groups[status]} selected={selected} toggle={toggle}/>) }
 {view!=='estoque'&&<div className="modalBackdrop"><div className="modal large"><button className="modalClose" onClick={()=>setView('estoque')}><X/></button>{view==='entrada'?<Entrada onDone={()=>{setMsg('Entrada por NF registrada. Movimento 101 e documento sequencial gerados.');setView('estoque')}}/>:view==='transferencia'?<Transferencia onDone={()=>{setMsg('Lote de transferência criado. Pneus permanecem EM TRANSFERÊNCIA até confirmação do destino.');setView('estoque')}}/>:<div/>}</div></div>}
 </div></AppShell>
}
function StockGroup({title,rows,selected,toggle}:{title:string;rows:Tire[];selected:string[];toggle:(f:string)=>void}){return <section className="section"><div className="sectionHead"><div className="sectionTitle"><span className="statusDot"/> {title}<span className="countBadge">{rows.length}</span></div></div><div className="tableWrap"><table className="table"><thead><tr><th></th><th>Material</th><th>Nº fogo</th><th>DOT</th><th>Marca / modelo</th><th>Medida</th><th>Vida</th><th>MM</th><th>Valor atual</th><th>KM acumulado</th><th>Status</th></tr></thead><tbody>{rows.map(t=><tr key={t.fogo}><td><input type="checkbox" checked={selected.includes(t.fogo)} onChange={()=>toggle(t.fogo)}/></td><td>{t.material} · {t.descricao}</td><td><b>{t.fogo}</b></td><td>{t.dot}</td><td>{t.marca} {t.modelo}</td><td>{t.medida}</td><td>{t.vida}</td><td>{t.mm.toFixed(1)} mm</td><td>R$ {t.valor.toLocaleString('pt-BR',{minimumFractionDigits:2})}</td><td>{t.km.toLocaleString('pt-BR')} km</td><td><span className={'pill '+(t.status==='NOVO'?'blue':t.status==='REFORMADO'?'green':t.status==='EM_REFORMA'?'purple':'warning')}>{t.status.replace('_',' ')}</span></td></tr>)}</tbody></table></div></section>}
function Entrada({onDone}:{onDone:()=>void}){return <><span className="eyebrow">MOVIMENTO 101</span><h3>Entrada de material por Nota Fiscal</h3><p>O cadastro individual de pneus novos só fica disponível após registrar a quantidade recebida.</p><div className="formGrid"><label>Número da NF<input defaultValue="45821"/></label><label>Data da NF<input type="date" defaultValue="2026-08-21"/></label><label>Fornecedor<select><option>Fornecedor de Pneus MG</option></select></label><label>Estoque destino<select><option>Estoque Principal · Matriz</option></select></label><label>Código material<input defaultValue="55"/></label><label>Quantidade<input type="number" defaultValue="10"/></label><label>Valor unitário<input defaultValue="2100,00"/></label><label>Valor total<input defaultValue="21000,00"/></label></div><div className="note">Ao confirmar, o sistema gera 10 pendências de cadastro individual. Cada número a fogo criado consome uma unidade da entrada fiscal.</div><button className="btn primary wide" onClick={onDone}>Registrar entrada e liberar cadastros</button></>}
function Transferencia({onDone}:{onDone:()=>void}){return <><span className="eyebrow">MOVIMENTO 601</span><h3>Transferência entre estoques</h3><div className="formGrid"><label>Unidade origem<select><option>BETMIX Matriz</option></select></label><label>Estoque origem<select><option>Estoque Principal</option></select></label><label>Unidade destino<select><option>Filial 02</option></select></label><label>Estoque destino<select><option>Estoque Pneus Filial 02</option></select></label></div><label className="field">Números a fogo<textarea defaultValue={'062505\n062507'} /></label><div className="note">Após a saída, os pneus ficam EM TRANSFERÊNCIA e indisponíveis para montagem até o destino confirmar o recebimento. Recebimento parcial é permitido.</div><button className="btn primary wide" onClick={onDone}>Criar lote de transferência</button></>}
